//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("CourtRegistersDBModel", "FK_tblRegisterBidder_tblCSI", "tblCSI", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CourtRegisters.tblCSI), "tblRegisterBidder", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CourtRegisters.tblRegisterBidder), true)]
[assembly: EdmRelationshipAttribute("CourtRegistersDBModel", "FK_tblRegisterProtocols_tblCSI", "tblCSI", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CourtRegisters.tblCSI), "tblRegisterProtocol", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CourtRegisters.tblRegisterProtocol), true)]
[assembly: EdmRelationshipAttribute("CourtRegistersDBModel", "FK_tblRegisterPublicSalesRooms_tblCSI", "tblCSI", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CourtRegisters.tblCSI), "tblRegisterPublicSalesRoom", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CourtRegisters.tblRegisterPublicSalesRoom), true)]

#endregion

namespace CourtRegisters
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CourtRegistersDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CourtRegistersDBEntities object using the connection string found in the 'CourtRegistersDBEntities' section of the application configuration file.
        /// </summary>
        public CourtRegistersDBEntities() : base("name=CourtRegistersDBEntities", "CourtRegistersDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CourtRegistersDBEntities object.
        /// </summary>
        public CourtRegistersDBEntities(string connectionString) : base(connectionString, "CourtRegistersDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CourtRegistersDBEntities object.
        /// </summary>
        public CourtRegistersDBEntities(EntityConnection connection) : base(connection, "CourtRegistersDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Counter> Counters
        {
            get
            {
                if ((_Counters == null))
                {
                    _Counters = base.CreateObjectSet<Counter>("Counters");
                }
                return _Counters;
            }
        }
        private ObjectSet<Counter> _Counters;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblCSI> tblCSIs
        {
            get
            {
                if ((_tblCSIs == null))
                {
                    _tblCSIs = base.CreateObjectSet<tblCSI>("tblCSIs");
                }
                return _tblCSIs;
            }
        }
        private ObjectSet<tblCSI> _tblCSIs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblRegisterBidder> tblRegisterBidders
        {
            get
            {
                if ((_tblRegisterBidders == null))
                {
                    _tblRegisterBidders = base.CreateObjectSet<tblRegisterBidder>("tblRegisterBidders");
                }
                return _tblRegisterBidders;
            }
        }
        private ObjectSet<tblRegisterBidder> _tblRegisterBidders;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblRegisterProtocol> tblRegisterProtocols
        {
            get
            {
                if ((_tblRegisterProtocols == null))
                {
                    _tblRegisterProtocols = base.CreateObjectSet<tblRegisterProtocol>("tblRegisterProtocols");
                }
                return _tblRegisterProtocols;
            }
        }
        private ObjectSet<tblRegisterProtocol> _tblRegisterProtocols;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblRegisterPublicSalesRoom> tblRegisterPublicSalesRooms
        {
            get
            {
                if ((_tblRegisterPublicSalesRooms == null))
                {
                    _tblRegisterPublicSalesRooms = base.CreateObjectSet<tblRegisterPublicSalesRoom>("tblRegisterPublicSalesRooms");
                }
                return _tblRegisterPublicSalesRooms;
            }
        }
        private ObjectSet<tblRegisterPublicSalesRoom> _tblRegisterPublicSalesRooms;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblSecurity> tblSecurities
        {
            get
            {
                if ((_tblSecurities == null))
                {
                    _tblSecurities = base.CreateObjectSet<tblSecurity>("tblSecurities");
                }
                return _tblSecurities;
            }
        }
        private ObjectSet<tblSecurity> _tblSecurities;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vwProtocolsForDay> vwProtocolsForDays
        {
            get
            {
                if ((_vwProtocolsForDays == null))
                {
                    _vwProtocolsForDays = base.CreateObjectSet<vwProtocolsForDay>("vwProtocolsForDays");
                }
                return _vwProtocolsForDays;
            }
        }
        private ObjectSet<vwProtocolsForDay> _vwProtocolsForDays;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Counters EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCounters(Counter counter)
        {
            base.AddObject("Counters", counter);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblCSIs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblCSIs(tblCSI tblCSI)
        {
            base.AddObject("tblCSIs", tblCSI);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblRegisterBidders EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblRegisterBidders(tblRegisterBidder tblRegisterBidder)
        {
            base.AddObject("tblRegisterBidders", tblRegisterBidder);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblRegisterProtocols EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblRegisterProtocols(tblRegisterProtocol tblRegisterProtocol)
        {
            base.AddObject("tblRegisterProtocols", tblRegisterProtocol);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblRegisterPublicSalesRooms EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblRegisterPublicSalesRooms(tblRegisterPublicSalesRoom tblRegisterPublicSalesRoom)
        {
            base.AddObject("tblRegisterPublicSalesRooms", tblRegisterPublicSalesRoom);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblSecurities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblSecurities(tblSecurity tblSecurity)
        {
            base.AddObject("tblSecurities", tblSecurity);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vwProtocolsForDays EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovwProtocolsForDays(vwProtocolsForDay vwProtocolsForDay)
        {
            base.AddObject("vwProtocolsForDays", vwProtocolsForDay);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="cSINumber">No Metadata Documentation available.</param>
        /// <param name="cSIName">No Metadata Documentation available.</param>
        public ObjectResult<Nullable<global::System.Int32>> Insert_CSI_SP(Nullable<global::System.Int32> cSINumber, global::System.String cSIName)
        {
            ObjectParameter cSINumberParameter;
            if (cSINumber.HasValue)
            {
                cSINumberParameter = new ObjectParameter("CSINumber", cSINumber);
            }
            else
            {
                cSINumberParameter = new ObjectParameter("CSINumber", typeof(global::System.Int32));
            }
    
            ObjectParameter cSINameParameter;
            if (cSIName != null)
            {
                cSINameParameter = new ObjectParameter("CSIName", cSIName);
            }
            else
            {
                cSINameParameter = new ObjectParameter("CSIName", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<Nullable<global::System.Int32>>("Insert_CSI_SP", cSINumberParameter, cSINameParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="iD">No Metadata Documentation available.</param>
        /// <param name="caseNumber">No Metadata Documentation available.</param>
        /// <param name="idCSI">No Metadata Documentation available.</param>
        /// <param name="bidderName">No Metadata Documentation available.</param>
        /// <param name="bidderAddress">No Metadata Documentation available.</param>
        /// <param name="postingDate">No Metadata Documentation available.</param>
        public ObjectResult<Nullable<global::System.Int32>> Insert_RegBidder_SP(Nullable<global::System.Int32> iD, global::System.String caseNumber, Nullable<global::System.Int32> idCSI, global::System.String bidderName, global::System.String bidderAddress, Nullable<global::System.DateTime> postingDate)
        {
            ObjectParameter iDParameter;
            if (iD.HasValue)
            {
                iDParameter = new ObjectParameter("ID", iD);
            }
            else
            {
                iDParameter = new ObjectParameter("ID", typeof(global::System.Int32));
            }
    
            ObjectParameter caseNumberParameter;
            if (caseNumber != null)
            {
                caseNumberParameter = new ObjectParameter("CaseNumber", caseNumber);
            }
            else
            {
                caseNumberParameter = new ObjectParameter("CaseNumber", typeof(global::System.String));
            }
    
            ObjectParameter idCSIParameter;
            if (idCSI.HasValue)
            {
                idCSIParameter = new ObjectParameter("IdCSI", idCSI);
            }
            else
            {
                idCSIParameter = new ObjectParameter("IdCSI", typeof(global::System.Int32));
            }
    
            ObjectParameter bidderNameParameter;
            if (bidderName != null)
            {
                bidderNameParameter = new ObjectParameter("BidderName", bidderName);
            }
            else
            {
                bidderNameParameter = new ObjectParameter("BidderName", typeof(global::System.String));
            }
    
            ObjectParameter bidderAddressParameter;
            if (bidderAddress != null)
            {
                bidderAddressParameter = new ObjectParameter("BidderAddress", bidderAddress);
            }
            else
            {
                bidderAddressParameter = new ObjectParameter("BidderAddress", typeof(global::System.String));
            }
    
            ObjectParameter postingDateParameter;
            if (postingDate.HasValue)
            {
                postingDateParameter = new ObjectParameter("PostingDate", postingDate);
            }
            else
            {
                postingDateParameter = new ObjectParameter("PostingDate", typeof(global::System.DateTime));
            }
    
            return base.ExecuteFunction<Nullable<global::System.Int32>>("Insert_RegBidder_SP", iDParameter, caseNumberParameter, idCSIParameter, bidderNameParameter, bidderAddressParameter, postingDateParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="iD">No Metadata Documentation available.</param>
        /// <param name="idCSI">No Metadata Documentation available.</param>
        /// <param name="publicSaleDateTime">No Metadata Documentation available.</param>
        /// <param name="publicSaleLocation">No Metadata Documentation available.</param>
        /// <param name="remarks">No Metadata Documentation available.</param>
        /// <param name="postingDate">No Metadata Documentation available.</param>
        public ObjectResult<Nullable<global::System.Int32>> Insert_RegSaleLocation_SP(Nullable<global::System.Int32> iD, Nullable<global::System.Int32> idCSI, Nullable<global::System.DateTime> publicSaleDateTime, global::System.String publicSaleLocation, global::System.String remarks, Nullable<global::System.DateTime> postingDate)
        {
            ObjectParameter iDParameter;
            if (iD.HasValue)
            {
                iDParameter = new ObjectParameter("ID", iD);
            }
            else
            {
                iDParameter = new ObjectParameter("ID", typeof(global::System.Int32));
            }
    
            ObjectParameter idCSIParameter;
            if (idCSI.HasValue)
            {
                idCSIParameter = new ObjectParameter("IdCSI", idCSI);
            }
            else
            {
                idCSIParameter = new ObjectParameter("IdCSI", typeof(global::System.Int32));
            }
    
            ObjectParameter publicSaleDateTimeParameter;
            if (publicSaleDateTime.HasValue)
            {
                publicSaleDateTimeParameter = new ObjectParameter("PublicSaleDateTime", publicSaleDateTime);
            }
            else
            {
                publicSaleDateTimeParameter = new ObjectParameter("PublicSaleDateTime", typeof(global::System.DateTime));
            }
    
            ObjectParameter publicSaleLocationParameter;
            if (publicSaleLocation != null)
            {
                publicSaleLocationParameter = new ObjectParameter("PublicSaleLocation", publicSaleLocation);
            }
            else
            {
                publicSaleLocationParameter = new ObjectParameter("PublicSaleLocation", typeof(global::System.String));
            }
    
            ObjectParameter remarksParameter;
            if (remarks != null)
            {
                remarksParameter = new ObjectParameter("Remarks", remarks);
            }
            else
            {
                remarksParameter = new ObjectParameter("Remarks", typeof(global::System.String));
            }
    
            ObjectParameter postingDateParameter;
            if (postingDate.HasValue)
            {
                postingDateParameter = new ObjectParameter("PostingDate", postingDate);
            }
            else
            {
                postingDateParameter = new ObjectParameter("PostingDate", typeof(global::System.DateTime));
            }
    
            return base.ExecuteFunction<Nullable<global::System.Int32>>("Insert_RegSaleLocation_SP", iDParameter, idCSIParameter, publicSaleDateTimeParameter, publicSaleLocationParameter, remarksParameter, postingDateParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="iD">No Metadata Documentation available.</param>
        /// <param name="caseNumber">No Metadata Documentation available.</param>
        /// <param name="idCSI">No Metadata Documentation available.</param>
        /// <param name="remarks">No Metadata Documentation available.</param>
        /// <param name="postingDate">No Metadata Documentation available.</param>
        public ObjectResult<Nullable<global::System.Int32>> Insert_RegProtocols_SP(Nullable<global::System.Int32> iD, global::System.String caseNumber, Nullable<global::System.Int32> idCSI, global::System.String remarks, Nullable<global::System.DateTime> postingDate)
        {
            ObjectParameter iDParameter;
            if (iD.HasValue)
            {
                iDParameter = new ObjectParameter("ID", iD);
            }
            else
            {
                iDParameter = new ObjectParameter("ID", typeof(global::System.Int32));
            }
    
            ObjectParameter caseNumberParameter;
            if (caseNumber != null)
            {
                caseNumberParameter = new ObjectParameter("CaseNumber", caseNumber);
            }
            else
            {
                caseNumberParameter = new ObjectParameter("CaseNumber", typeof(global::System.String));
            }
    
            ObjectParameter idCSIParameter;
            if (idCSI.HasValue)
            {
                idCSIParameter = new ObjectParameter("IdCSI", idCSI);
            }
            else
            {
                idCSIParameter = new ObjectParameter("IdCSI", typeof(global::System.Int32));
            }
    
            ObjectParameter remarksParameter;
            if (remarks != null)
            {
                remarksParameter = new ObjectParameter("Remarks", remarks);
            }
            else
            {
                remarksParameter = new ObjectParameter("Remarks", typeof(global::System.String));
            }
    
            ObjectParameter postingDateParameter;
            if (postingDate.HasValue)
            {
                postingDateParameter = new ObjectParameter("PostingDate", postingDate);
            }
            else
            {
                postingDateParameter = new ObjectParameter("PostingDate", typeof(global::System.DateTime));
            }
    
            return base.ExecuteFunction<Nullable<global::System.Int32>>("Insert_RegProtocols_SP", iDParameter, caseNumberParameter, idCSIParameter, remarksParameter, postingDateParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="postingDate">No Metadata Documentation available.</param>
        public ObjectResult<BidderByDate> Get_BidderByDate_SP(Nullable<global::System.DateTime> postingDate)
        {
            ObjectParameter postingDateParameter;
            if (postingDate.HasValue)
            {
                postingDateParameter = new ObjectParameter("PostingDate", postingDate);
            }
            else
            {
                postingDateParameter = new ObjectParameter("PostingDate", typeof(global::System.DateTime));
            }
    
            return base.ExecuteFunction<BidderByDate>("Get_BidderByDate_SP", postingDateParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CourtRegistersDBModel", Name="Counter")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Counter : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Counter object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="tableEnum">Initial value of the TableEnum property.</param>
        /// <param name="lastNum">Initial value of the LastNum property.</param>
        /// <param name="year">Initial value of the Year property.</param>
        public static Counter CreateCounter(global::System.Int32 id, global::System.Int32 tableEnum, global::System.Int32 lastNum, global::System.Int32 year)
        {
            Counter counter = new Counter();
            counter.Id = id;
            counter.TableEnum = tableEnum;
            counter.LastNum = lastNum;
            counter.Year = year;
            return counter;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TableEnum
        {
            get
            {
                return _TableEnum;
            }
            set
            {
                OnTableEnumChanging(value);
                ReportPropertyChanging("TableEnum");
                _TableEnum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TableEnum");
                OnTableEnumChanged();
            }
        }
        private global::System.Int32 _TableEnum;
        partial void OnTableEnumChanging(global::System.Int32 value);
        partial void OnTableEnumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LastNum
        {
            get
            {
                return _LastNum;
            }
            set
            {
                OnLastNumChanging(value);
                ReportPropertyChanging("LastNum");
                _LastNum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastNum");
                OnLastNumChanged();
            }
        }
        private global::System.Int32 _LastNum;
        partial void OnLastNumChanging(global::System.Int32 value);
        partial void OnLastNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NextNum
        {
            get
            {
                return _NextNum;
            }
            set
            {
                OnNextNumChanging(value);
                ReportPropertyChanging("NextNum");
                _NextNum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NextNum");
                OnNextNumChanged();
            }
        }
        private Nullable<global::System.Int32> _NextNum;
        partial void OnNextNumChanging(Nullable<global::System.Int32> value);
        partial void OnNextNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Year
        {
            get
            {
                return _Year;
            }
            set
            {
                OnYearChanging(value);
                ReportPropertyChanging("Year");
                _Year = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Year");
                OnYearChanged();
            }
        }
        private global::System.Int32 _Year;
        partial void OnYearChanging(global::System.Int32 value);
        partial void OnYearChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CourtRegistersDBModel", Name="tblCSI")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblCSI : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblCSI object.
        /// </summary>
        /// <param name="idCSI">Initial value of the IdCSI property.</param>
        /// <param name="cSINumber">Initial value of the CSINumber property.</param>
        /// <param name="isActive">Initial value of the IsActive property.</param>
        public static tblCSI CreatetblCSI(global::System.Int32 idCSI, global::System.Int32 cSINumber, global::System.Boolean isActive)
        {
            tblCSI tblCSI = new tblCSI();
            tblCSI.IdCSI = idCSI;
            tblCSI.CSINumber = cSINumber;
            tblCSI.IsActive = isActive;
            return tblCSI;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCSI
        {
            get
            {
                return _IdCSI;
            }
            set
            {
                if (_IdCSI != value)
                {
                    OnIdCSIChanging(value);
                    ReportPropertyChanging("IdCSI");
                    _IdCSI = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdCSI");
                    OnIdCSIChanged();
                }
            }
        }
        private global::System.Int32 _IdCSI;
        partial void OnIdCSIChanging(global::System.Int32 value);
        partial void OnIdCSIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CSINumber
        {
            get
            {
                return _CSINumber;
            }
            set
            {
                OnCSINumberChanging(value);
                ReportPropertyChanging("CSINumber");
                _CSINumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CSINumber");
                OnCSINumberChanged();
            }
        }
        private global::System.Int32 _CSINumber;
        partial void OnCSINumberChanging(global::System.Int32 value);
        partial void OnCSINumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CSIName
        {
            get
            {
                return _CSIName;
            }
            set
            {
                OnCSINameChanging(value);
                ReportPropertyChanging("CSIName");
                _CSIName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CSIName");
                OnCSINameChanged();
            }
        }
        private global::System.String _CSIName;
        partial void OnCSINameChanging(global::System.String value);
        partial void OnCSINameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private global::System.Boolean _IsActive;
        partial void OnIsActiveChanging(global::System.Boolean value);
        partial void OnIsActiveChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CourtRegistersDBModel", "FK_tblRegisterBidder_tblCSI", "tblRegisterBidder")]
        public EntityCollection<tblRegisterBidder> tblRegisterBidders
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblRegisterBidder>("CourtRegistersDBModel.FK_tblRegisterBidder_tblCSI", "tblRegisterBidder");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblRegisterBidder>("CourtRegistersDBModel.FK_tblRegisterBidder_tblCSI", "tblRegisterBidder", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CourtRegistersDBModel", "FK_tblRegisterProtocols_tblCSI", "tblRegisterProtocol")]
        public EntityCollection<tblRegisterProtocol> tblRegisterProtocols
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblRegisterProtocol>("CourtRegistersDBModel.FK_tblRegisterProtocols_tblCSI", "tblRegisterProtocol");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblRegisterProtocol>("CourtRegistersDBModel.FK_tblRegisterProtocols_tblCSI", "tblRegisterProtocol", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CourtRegistersDBModel", "FK_tblRegisterPublicSalesRooms_tblCSI", "tblRegisterPublicSalesRoom")]
        public EntityCollection<tblRegisterPublicSalesRoom> tblRegisterPublicSalesRooms
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblRegisterPublicSalesRoom>("CourtRegistersDBModel.FK_tblRegisterPublicSalesRooms_tblCSI", "tblRegisterPublicSalesRoom");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblRegisterPublicSalesRoom>("CourtRegistersDBModel.FK_tblRegisterPublicSalesRooms_tblCSI", "tblRegisterPublicSalesRoom", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CourtRegistersDBModel", Name="tblRegisterBidder")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblRegisterBidder : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblRegisterBidder object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="incomeNumber">Initial value of the IncomeNumber property.</param>
        /// <param name="caseNumber">Initial value of the CaseNumber property.</param>
        /// <param name="idCSI">Initial value of the IdCSI property.</param>
        /// <param name="bidderName">Initial value of the BidderName property.</param>
        /// <param name="bidderAddress">Initial value of the BidderAddress property.</param>
        /// <param name="postingDate">Initial value of the PostingDate property.</param>
        public static tblRegisterBidder CreatetblRegisterBidder(global::System.Int32 id, global::System.Int32 incomeNumber, global::System.String caseNumber, global::System.Int32 idCSI, global::System.String bidderName, global::System.String bidderAddress, global::System.DateTime postingDate)
        {
            tblRegisterBidder tblRegisterBidder = new tblRegisterBidder();
            tblRegisterBidder.ID = id;
            tblRegisterBidder.IncomeNumber = incomeNumber;
            tblRegisterBidder.CaseNumber = caseNumber;
            tblRegisterBidder.IdCSI = idCSI;
            tblRegisterBidder.BidderName = bidderName;
            tblRegisterBidder.BidderAddress = bidderAddress;
            tblRegisterBidder.PostingDate = postingDate;
            return tblRegisterBidder;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IncomeNumber
        {
            get
            {
                return _IncomeNumber;
            }
            set
            {
                OnIncomeNumberChanging(value);
                ReportPropertyChanging("IncomeNumber");
                _IncomeNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IncomeNumber");
                OnIncomeNumberChanged();
            }
        }
        private global::System.Int32 _IncomeNumber;
        partial void OnIncomeNumberChanging(global::System.Int32 value);
        partial void OnIncomeNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CaseNumber
        {
            get
            {
                return _CaseNumber;
            }
            set
            {
                OnCaseNumberChanging(value);
                ReportPropertyChanging("CaseNumber");
                _CaseNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CaseNumber");
                OnCaseNumberChanged();
            }
        }
        private global::System.String _CaseNumber;
        partial void OnCaseNumberChanging(global::System.String value);
        partial void OnCaseNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCSI
        {
            get
            {
                return _IdCSI;
            }
            set
            {
                OnIdCSIChanging(value);
                ReportPropertyChanging("IdCSI");
                _IdCSI = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdCSI");
                OnIdCSIChanged();
            }
        }
        private global::System.Int32 _IdCSI;
        partial void OnIdCSIChanging(global::System.Int32 value);
        partial void OnIdCSIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BidderName
        {
            get
            {
                return _BidderName;
            }
            set
            {
                OnBidderNameChanging(value);
                ReportPropertyChanging("BidderName");
                _BidderName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BidderName");
                OnBidderNameChanged();
            }
        }
        private global::System.String _BidderName;
        partial void OnBidderNameChanging(global::System.String value);
        partial void OnBidderNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BidderAddress
        {
            get
            {
                return _BidderAddress;
            }
            set
            {
                OnBidderAddressChanging(value);
                ReportPropertyChanging("BidderAddress");
                _BidderAddress = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BidderAddress");
                OnBidderAddressChanged();
            }
        }
        private global::System.String _BidderAddress;
        partial void OnBidderAddressChanging(global::System.String value);
        partial void OnBidderAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime PostingDate
        {
            get
            {
                return _PostingDate;
            }
            set
            {
                OnPostingDateChanging(value);
                ReportPropertyChanging("PostingDate");
                _PostingDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PostingDate");
                OnPostingDateChanged();
            }
        }
        private global::System.DateTime _PostingDate;
        partial void OnPostingDateChanging(global::System.DateTime value);
        partial void OnPostingDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CourtRegistersDBModel", "FK_tblRegisterBidder_tblCSI", "tblCSI")]
        public tblCSI tblCSI
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblCSI>("CourtRegistersDBModel.FK_tblRegisterBidder_tblCSI", "tblCSI").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblCSI>("CourtRegistersDBModel.FK_tblRegisterBidder_tblCSI", "tblCSI").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblCSI> tblCSIReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblCSI>("CourtRegistersDBModel.FK_tblRegisterBidder_tblCSI", "tblCSI");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblCSI>("CourtRegistersDBModel.FK_tblRegisterBidder_tblCSI", "tblCSI", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CourtRegistersDBModel", Name="tblRegisterProtocol")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblRegisterProtocol : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblRegisterProtocol object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="incomeNumber">Initial value of the IncomeNumber property.</param>
        /// <param name="idCSI">Initial value of the IdCSI property.</param>
        /// <param name="caseNumber">Initial value of the CaseNumber property.</param>
        /// <param name="postingDate">Initial value of the PostingDate property.</param>
        public static tblRegisterProtocol CreatetblRegisterProtocol(global::System.Int32 id, global::System.Int32 incomeNumber, global::System.Int32 idCSI, global::System.String caseNumber, global::System.DateTime postingDate)
        {
            tblRegisterProtocol tblRegisterProtocol = new tblRegisterProtocol();
            tblRegisterProtocol.ID = id;
            tblRegisterProtocol.IncomeNumber = incomeNumber;
            tblRegisterProtocol.IdCSI = idCSI;
            tblRegisterProtocol.CaseNumber = caseNumber;
            tblRegisterProtocol.PostingDate = postingDate;
            return tblRegisterProtocol;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IncomeNumber
        {
            get
            {
                return _IncomeNumber;
            }
            set
            {
                OnIncomeNumberChanging(value);
                ReportPropertyChanging("IncomeNumber");
                _IncomeNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IncomeNumber");
                OnIncomeNumberChanged();
            }
        }
        private global::System.Int32 _IncomeNumber;
        partial void OnIncomeNumberChanging(global::System.Int32 value);
        partial void OnIncomeNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCSI
        {
            get
            {
                return _IdCSI;
            }
            set
            {
                OnIdCSIChanging(value);
                ReportPropertyChanging("IdCSI");
                _IdCSI = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdCSI");
                OnIdCSIChanged();
            }
        }
        private global::System.Int32 _IdCSI;
        partial void OnIdCSIChanging(global::System.Int32 value);
        partial void OnIdCSIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CaseNumber
        {
            get
            {
                return _CaseNumber;
            }
            set
            {
                OnCaseNumberChanging(value);
                ReportPropertyChanging("CaseNumber");
                _CaseNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CaseNumber");
                OnCaseNumberChanged();
            }
        }
        private global::System.String _CaseNumber;
        partial void OnCaseNumberChanging(global::System.String value);
        partial void OnCaseNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime PostingDate
        {
            get
            {
                return _PostingDate;
            }
            set
            {
                OnPostingDateChanging(value);
                ReportPropertyChanging("PostingDate");
                _PostingDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PostingDate");
                OnPostingDateChanged();
            }
        }
        private global::System.DateTime _PostingDate;
        partial void OnPostingDateChanging(global::System.DateTime value);
        partial void OnPostingDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Remarks
        {
            get
            {
                return _Remarks;
            }
            set
            {
                OnRemarksChanging(value);
                ReportPropertyChanging("Remarks");
                _Remarks = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Remarks");
                OnRemarksChanged();
            }
        }
        private global::System.String _Remarks;
        partial void OnRemarksChanging(global::System.String value);
        partial void OnRemarksChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CourtRegistersDBModel", "FK_tblRegisterProtocols_tblCSI", "tblCSI")]
        public tblCSI tblCSI
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblCSI>("CourtRegistersDBModel.FK_tblRegisterProtocols_tblCSI", "tblCSI").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblCSI>("CourtRegistersDBModel.FK_tblRegisterProtocols_tblCSI", "tblCSI").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblCSI> tblCSIReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblCSI>("CourtRegistersDBModel.FK_tblRegisterProtocols_tblCSI", "tblCSI");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblCSI>("CourtRegistersDBModel.FK_tblRegisterProtocols_tblCSI", "tblCSI", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CourtRegistersDBModel", Name="tblRegisterPublicSalesRoom")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblRegisterPublicSalesRoom : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblRegisterPublicSalesRoom object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="incomeNumber">Initial value of the IncomeNumber property.</param>
        /// <param name="idCSI">Initial value of the IdCSI property.</param>
        /// <param name="publicSaleDateTime">Initial value of the PublicSaleDateTime property.</param>
        /// <param name="publicSaleLocation">Initial value of the PublicSaleLocation property.</param>
        /// <param name="postingDate">Initial value of the PostingDate property.</param>
        public static tblRegisterPublicSalesRoom CreatetblRegisterPublicSalesRoom(global::System.Int32 id, global::System.Int32 incomeNumber, global::System.Int32 idCSI, global::System.DateTime publicSaleDateTime, global::System.String publicSaleLocation, global::System.DateTime postingDate)
        {
            tblRegisterPublicSalesRoom tblRegisterPublicSalesRoom = new tblRegisterPublicSalesRoom();
            tblRegisterPublicSalesRoom.ID = id;
            tblRegisterPublicSalesRoom.IncomeNumber = incomeNumber;
            tblRegisterPublicSalesRoom.IdCSI = idCSI;
            tblRegisterPublicSalesRoom.PublicSaleDateTime = publicSaleDateTime;
            tblRegisterPublicSalesRoom.PublicSaleLocation = publicSaleLocation;
            tblRegisterPublicSalesRoom.PostingDate = postingDate;
            return tblRegisterPublicSalesRoom;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IncomeNumber
        {
            get
            {
                return _IncomeNumber;
            }
            set
            {
                OnIncomeNumberChanging(value);
                ReportPropertyChanging("IncomeNumber");
                _IncomeNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IncomeNumber");
                OnIncomeNumberChanged();
            }
        }
        private global::System.Int32 _IncomeNumber;
        partial void OnIncomeNumberChanging(global::System.Int32 value);
        partial void OnIncomeNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCSI
        {
            get
            {
                return _IdCSI;
            }
            set
            {
                OnIdCSIChanging(value);
                ReportPropertyChanging("IdCSI");
                _IdCSI = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdCSI");
                OnIdCSIChanged();
            }
        }
        private global::System.Int32 _IdCSI;
        partial void OnIdCSIChanging(global::System.Int32 value);
        partial void OnIdCSIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime PublicSaleDateTime
        {
            get
            {
                return _PublicSaleDateTime;
            }
            set
            {
                OnPublicSaleDateTimeChanging(value);
                ReportPropertyChanging("PublicSaleDateTime");
                _PublicSaleDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PublicSaleDateTime");
                OnPublicSaleDateTimeChanged();
            }
        }
        private global::System.DateTime _PublicSaleDateTime;
        partial void OnPublicSaleDateTimeChanging(global::System.DateTime value);
        partial void OnPublicSaleDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PublicSaleLocation
        {
            get
            {
                return _PublicSaleLocation;
            }
            set
            {
                OnPublicSaleLocationChanging(value);
                ReportPropertyChanging("PublicSaleLocation");
                _PublicSaleLocation = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PublicSaleLocation");
                OnPublicSaleLocationChanged();
            }
        }
        private global::System.String _PublicSaleLocation;
        partial void OnPublicSaleLocationChanging(global::System.String value);
        partial void OnPublicSaleLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime PostingDate
        {
            get
            {
                return _PostingDate;
            }
            set
            {
                OnPostingDateChanging(value);
                ReportPropertyChanging("PostingDate");
                _PostingDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PostingDate");
                OnPostingDateChanged();
            }
        }
        private global::System.DateTime _PostingDate;
        partial void OnPostingDateChanging(global::System.DateTime value);
        partial void OnPostingDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Remarks
        {
            get
            {
                return _Remarks;
            }
            set
            {
                OnRemarksChanging(value);
                ReportPropertyChanging("Remarks");
                _Remarks = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Remarks");
                OnRemarksChanged();
            }
        }
        private global::System.String _Remarks;
        partial void OnRemarksChanging(global::System.String value);
        partial void OnRemarksChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CourtRegistersDBModel", "FK_tblRegisterPublicSalesRooms_tblCSI", "tblCSI")]
        public tblCSI tblCSI
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblCSI>("CourtRegistersDBModel.FK_tblRegisterPublicSalesRooms_tblCSI", "tblCSI").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblCSI>("CourtRegistersDBModel.FK_tblRegisterPublicSalesRooms_tblCSI", "tblCSI").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblCSI> tblCSIReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblCSI>("CourtRegistersDBModel.FK_tblRegisterPublicSalesRooms_tblCSI", "tblCSI");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblCSI>("CourtRegistersDBModel.FK_tblRegisterPublicSalesRooms_tblCSI", "tblCSI", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CourtRegistersDBModel", Name="tblSecurity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblSecurity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblSecurity object.
        /// </summary>
        /// <param name="idSec">Initial value of the IdSec property.</param>
        /// <param name="court">Initial value of the Court property.</param>
        /// <param name="hashValue">Initial value of the HashValue property.</param>
        public static tblSecurity CreatetblSecurity(global::System.Int32 idSec, global::System.String court, global::System.String hashValue)
        {
            tblSecurity tblSecurity = new tblSecurity();
            tblSecurity.IdSec = idSec;
            tblSecurity.Court = court;
            tblSecurity.HashValue = hashValue;
            return tblSecurity;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdSec
        {
            get
            {
                return _IdSec;
            }
            set
            {
                if (_IdSec != value)
                {
                    OnIdSecChanging(value);
                    ReportPropertyChanging("IdSec");
                    _IdSec = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdSec");
                    OnIdSecChanged();
                }
            }
        }
        private global::System.Int32 _IdSec;
        partial void OnIdSecChanging(global::System.Int32 value);
        partial void OnIdSecChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Court
        {
            get
            {
                return _Court;
            }
            set
            {
                OnCourtChanging(value);
                ReportPropertyChanging("Court");
                _Court = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Court");
                OnCourtChanged();
            }
        }
        private global::System.String _Court;
        partial void OnCourtChanging(global::System.String value);
        partial void OnCourtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HashValue
        {
            get
            {
                return _HashValue;
            }
            set
            {
                OnHashValueChanging(value);
                ReportPropertyChanging("HashValue");
                _HashValue = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("HashValue");
                OnHashValueChanged();
            }
        }
        private global::System.String _HashValue;
        partial void OnHashValueChanging(global::System.String value);
        partial void OnHashValueChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CourtRegistersDBModel", Name="vwProtocolsForDay")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vwProtocolsForDay : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vwProtocolsForDay object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="incomeNumber">Initial value of the IncomeNumber property.</param>
        /// <param name="caseNumber">Initial value of the CaseNumber property.</param>
        /// <param name="postingDate">Initial value of the PostingDate property.</param>
        /// <param name="idCSI">Initial value of the IdCSI property.</param>
        public static vwProtocolsForDay CreatevwProtocolsForDay(global::System.Int32 id, global::System.Int32 incomeNumber, global::System.String caseNumber, global::System.DateTime postingDate, global::System.Int32 idCSI)
        {
            vwProtocolsForDay vwProtocolsForDay = new vwProtocolsForDay();
            vwProtocolsForDay.ID = id;
            vwProtocolsForDay.IncomeNumber = incomeNumber;
            vwProtocolsForDay.CaseNumber = caseNumber;
            vwProtocolsForDay.PostingDate = postingDate;
            vwProtocolsForDay.IdCSI = idCSI;
            return vwProtocolsForDay;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IncomeNumber
        {
            get
            {
                return _IncomeNumber;
            }
            set
            {
                if (_IncomeNumber != value)
                {
                    OnIncomeNumberChanging(value);
                    ReportPropertyChanging("IncomeNumber");
                    _IncomeNumber = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IncomeNumber");
                    OnIncomeNumberChanged();
                }
            }
        }
        private global::System.Int32 _IncomeNumber;
        partial void OnIncomeNumberChanging(global::System.Int32 value);
        partial void OnIncomeNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CaseNumber
        {
            get
            {
                return _CaseNumber;
            }
            set
            {
                if (_CaseNumber != value)
                {
                    OnCaseNumberChanging(value);
                    ReportPropertyChanging("CaseNumber");
                    _CaseNumber = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CaseNumber");
                    OnCaseNumberChanged();
                }
            }
        }
        private global::System.String _CaseNumber;
        partial void OnCaseNumberChanging(global::System.String value);
        partial void OnCaseNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime PostingDate
        {
            get
            {
                return _PostingDate;
            }
            set
            {
                if (_PostingDate != value)
                {
                    OnPostingDateChanging(value);
                    ReportPropertyChanging("PostingDate");
                    _PostingDate = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PostingDate");
                    OnPostingDateChanged();
                }
            }
        }
        private global::System.DateTime _PostingDate;
        partial void OnPostingDateChanging(global::System.DateTime value);
        partial void OnPostingDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCSI
        {
            get
            {
                return _IdCSI;
            }
            set
            {
                if (_IdCSI != value)
                {
                    OnIdCSIChanging(value);
                    ReportPropertyChanging("IdCSI");
                    _IdCSI = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdCSI");
                    OnIdCSIChanged();
                }
            }
        }
        private global::System.Int32 _IdCSI;
        partial void OnIdCSIChanging(global::System.Int32 value);
        partial void OnIdCSIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CSIName
        {
            get
            {
                return _CSIName;
            }
            set
            {
                OnCSINameChanging(value);
                ReportPropertyChanging("CSIName");
                _CSIName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CSIName");
                OnCSINameChanged();
            }
        }
        private global::System.String _CSIName;
        partial void OnCSINameChanging(global::System.String value);
        partial void OnCSINameChanged();

        #endregion

    
    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="CourtRegistersDBModel", Name="BidderByDate")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class BidderByDate : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BidderByDate object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="incomeNumber">Initial value of the IncomeNumber property.</param>
        /// <param name="caseNumber">Initial value of the CaseNumber property.</param>
        /// <param name="bidderName">Initial value of the BidderName property.</param>
        /// <param name="bidderAddress">Initial value of the BidderAddress property.</param>
        /// <param name="postingDate">Initial value of the PostingDate property.</param>
        public static BidderByDate CreateBidderByDate(global::System.Int32 id, global::System.Int32 incomeNumber, global::System.String caseNumber, global::System.String bidderName, global::System.String bidderAddress, global::System.DateTime postingDate)
        {
            BidderByDate bidderByDate = new BidderByDate();
            bidderByDate.ID = id;
            bidderByDate.IncomeNumber = incomeNumber;
            bidderByDate.CaseNumber = caseNumber;
            bidderByDate.BidderName = bidderName;
            bidderByDate.BidderAddress = bidderAddress;
            bidderByDate.PostingDate = postingDate;
            return bidderByDate;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                OnIDChanging(value);
                ReportPropertyChanging("ID");
                _ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID");
                OnIDChanged();
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IncomeNumber
        {
            get
            {
                return _IncomeNumber;
            }
            set
            {
                OnIncomeNumberChanging(value);
                ReportPropertyChanging("IncomeNumber");
                _IncomeNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IncomeNumber");
                OnIncomeNumberChanged();
            }
        }
        private global::System.Int32 _IncomeNumber;
        partial void OnIncomeNumberChanging(global::System.Int32 value);
        partial void OnIncomeNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CaseNumber
        {
            get
            {
                return _CaseNumber;
            }
            set
            {
                OnCaseNumberChanging(value);
                ReportPropertyChanging("CaseNumber");
                _CaseNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CaseNumber");
                OnCaseNumberChanged();
            }
        }
        private global::System.String _CaseNumber;
        partial void OnCaseNumberChanging(global::System.String value);
        partial void OnCaseNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CSIName
        {
            get
            {
                return _CSIName;
            }
            set
            {
                OnCSINameChanging(value);
                ReportPropertyChanging("CSIName");
                _CSIName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CSIName");
                OnCSINameChanged();
            }
        }
        private global::System.String _CSIName;
        partial void OnCSINameChanging(global::System.String value);
        partial void OnCSINameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BidderName
        {
            get
            {
                return _BidderName;
            }
            set
            {
                OnBidderNameChanging(value);
                ReportPropertyChanging("BidderName");
                _BidderName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BidderName");
                OnBidderNameChanged();
            }
        }
        private global::System.String _BidderName;
        partial void OnBidderNameChanging(global::System.String value);
        partial void OnBidderNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BidderAddress
        {
            get
            {
                return _BidderAddress;
            }
            set
            {
                OnBidderAddressChanging(value);
                ReportPropertyChanging("BidderAddress");
                _BidderAddress = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BidderAddress");
                OnBidderAddressChanged();
            }
        }
        private global::System.String _BidderAddress;
        partial void OnBidderAddressChanging(global::System.String value);
        partial void OnBidderAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime PostingDate
        {
            get
            {
                return _PostingDate;
            }
            set
            {
                OnPostingDateChanging(value);
                ReportPropertyChanging("PostingDate");
                _PostingDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PostingDate");
                OnPostingDateChanged();
            }
        }
        private global::System.DateTime _PostingDate;
        partial void OnPostingDateChanging(global::System.DateTime value);
        partial void OnPostingDateChanged();

        #endregion

    }

    #endregion

    
}
